application_secret: 7d8fe9e9-04fc-42a8-9577-40ecc40d27d7
log_level: info
otel:
  exporter_otlp_endpoint: http://0.0.0.0:4317
master_keys:
  - my-key-123
host: 127.0.0.1
port: 8082
database_configuration:
  engine: postgres
  host: localhost
  port: 5432
  database: llmur
  username: postgres
  password: postgres
cache_configuration:
  engine: redis
  host: localhost
  port: 6379
  username: default
  password: redispassword